#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

#### What kind of areray to be used to deal with numpy
Homogeneous arrays: Require all inner lists to have the same length.

#### If hetrogenous are used then it will be deal like this
Padding: Use padding to equalize lengths and leverage NumPy's performance.

Object arrays: Allow for varying lengths but with reduced performance and functionality.

In [68]:
!pip install numpy


In [12]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)  #output---> (5,) it is a represtation of 1d array
arr.reshape(1,5)       #output---> (1,5) 1 row and 5 column 


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


array([[1, 2, 3, 4, 5]])

In [ ]:
# np.arr([1,2,3,4]) ---> this is representation of 1 d array
# np.arr([[1,2,3,4]]) ---> this is representation of 2 d array

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5]])

print(arr1.shape)
print(arr2.shape)

(5,)
(1, 5)


In [16]:
## 2d array
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("array: \n",arr3)
print(arr3.shape)
np.arange(0,10,2).reshape(1,5)


array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


array([[0, 2, 4, 6, 8]])

In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [21]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [51]:
## array slicing and Indexing --> this is used to retrive any row,column, data from the array
arr = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
print("array: \n",arr)
print("\n",arr[1:])
print("\n",arr[1:2])
print("\n",arr[0:,4:])
print("\n",arr[0:,2:3])
print("\n",arr[1:2,3:4])
print("\n",arr[2:3,4:5])
print("\n",arr[2:3,3:4])
print("\n",arr[1:,2:4])




array: 
 [[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]

 [[2 3 4 5 6]
 [3 4 5 6 7]]

 [[2 3 4 5 6]]

 [[5]
 [6]
 [7]]

 [[3]
 [4]
 [5]]

 [[5]]

 [[7]]

 [[6]]

 [[4 5]
 [5 6]]


In [52]:
## Modify array elements
arr[0,0] = 30
print(arr)

[[30  2  3  4  5]
 [ 2  3  4  5  6]
 [ 3  4  5  6  7]]


In [53]:

arr[1:2,0:] = 40
print(arr)

[[30  2  3  4  5]
 [40 40 40 40 40]
 [ 3  4  5  6  7]]


In [38]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.array([1,2,3,4,5,3,6,7,8])

mean = np.mean(data)
print("mean: ",mean)

median = np.median(data)
print("median: ",median)

standard_devaiation = np.std(data)
print("mode: ",standard_devaiation)

var = np.var(data)
print("variance: ",var)

mean:  4.333333333333333
median:  4.0
mode:  2.211083193570267
variance:  4.888888888888889


In [66]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]
data[(data>3) & (data<5)]

array([4])

In [ ]:
## Attributes of Numpy Array
arrx = np.array([[1,2,3,4,5],[3,4,5,6,7],[2,5,6,7,8]])
print("Array: \n",arrx)
print("dimension: ",arrx.ndim)
print("size: ",arrx.size)
print("shape: ",arrx.shape)
print("datatype: ",arr.dtype)
print("itemsize: ",arr.itemsize)



Array: 
 [[1 2 3 4 5]
 [3 4 5 6 7]
 [2 5 6 7 8]]
dimension:  2
size:  15
shape:  (3, 5)
datatype:  int32
itemsize:  4


In [ ]:
# functions in numpy
np.array      #--> creates array
arr.shape     # --> provide the shape of the given array
arr.reshape   #--> converts 1d ayyary to 2d or some other type
np.arrange    #--> creates an array on the basis of some conditions
np.ones       #--> create a matrix with only value as 1
np.eye        #--> create identity matrix
np.sqrt
np.log
np.sin
np.mean
np.var
np.std
np.median
np.exp
np.random.randint(1,10,size=(2,2))   # this mean we need to create an 2D array with shape 4*4 and its element to be filled between 1 to 10 randomly
np.random.randint(1,10,size=(2,))    # this mean we need to create an 1D array with 5 element to be filled between 1 to 10 randomly
np.fill_diagonal(array,0)  # this will the diagonal elements with the number which we will give
np.concatenate((array[0,0:],array[4,0:],array[1:4,0],array[1:4,4]))         #concatinate different arrays
np.sum(array,axis=1)    # used to compute the sum of row 
np.sum(array,axis=0)    # # used to compute the sum of column 
np.linalg.()     # used to solve various mathematical operations like matrix,determinats,eigen values, Machine learning (e.g., multivariate Gaussian distribution),solving linear equations
np.dot()   # perform matrix multiplication
np.random.choice(['A','B','C']size=(2,2))      # this mean we need to create an 2D array with shape 2*2 and its element to be filled between A to C randomly

ways of cretaing arrays using numpy
1) np.array([1,2,3,4,4])
1) np.array([1,2,3,4,4][2,3,4,5,6])
3) np.random.randint(1,11,size=(3,3))
4) np.arrange(1,5).reshape(3,3)



#### BROADCASTING OF ARRAY
Broadcasting in NumPy is a powerful feature that allows arithmetic operations between arrays of different shapes—without explicitly replicating data.

iT CAN BE OF TWO TYPES:-

Scalar + Array

2D + 1D Array

In [69]:
#SCALAR + ARRAY
import numpy as np
arr = np.array([1, 2, 3])
print(arr + 10)


[11 12 13]


In [ ]:
# 2D + 1D Array
A = np.array([[1, 2, 3],
            [4, 5, 6]])
B = np.array([10, 20, 30])

print(A + B)


[[11 22 33]
 [14 25 36]]
