# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1. -->

In [ ]:
import numpy as np
array=np.random.randint(1,21,size=(5,5))
print("Arrya: \n",array)

array[0:,2:3] = 1
print("modified array: \n",array)


Arrya: 
 [[10 16 16 20  8]
 [14 16 15  5  1]
 [13 12 14 12 20]
 [ 4  4 18  3  5]
 [ 9 20 12 19 17]]
modified array: 
 [[10 16  1 20  8]
 [14 16  1  5  1]
 [13 12  1 12 20]
 [ 4  4  1  3  5]
 [ 9 20  1 19 17]]


 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0. 

In [ ]:
import numpy as np
array = np.arange(1,17).reshape((4,4))
print("Array: \n", array)

np.fill_diagonal(array,0)
print("modified array: \n",array)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
modified array: 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


 ### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [ ]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36

array = np.arange(1,37).reshape((6,6))
print("array: \n",array)

sub_array = array[2:5,1:4]
print("modified array: \n",sub_array)

array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
modified array: 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [ ]:
# Create a NumPy array of shape (5, 5) with random integers

array = np.random.randint(1,21,size=(5,5))
print("array: \n",array)

border_elements = np.concatenate((array[0,0:],array[4,0:],array[1:4,0],array[1:4,4]))
print("Border elements:")
print(border_elements)


array: 
 [[ 5 16 13  6 12]
 [ 1  3 13  2  7]
 [ 4 13 13 11 10]
 [18 16 20 16  9]
 [17 20 15 11 17]]
Border elements:
[ 5 16 13  6 12 17 20 15 11 17  1  4 18  7 10  9]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
# Create two NumPy arrays of shape (3, 4) filled with random integers

array1 = np.random.randint(1,11,size=(3,4))
array2 = np.random.randint(1,11,size=(3,4))

print("Array1: \n",array1)
print("Array2: \n",array2)

add = array1 + array2
print("addition: \n",add)

sub = array1 - array2
print("Substraction: \n",sub)

mult = array1 * array2
print("multiplication: \n",mult)

divide = array1 / array2
print("division: \n",divide)


Array1: 
 [[ 6  4  7 10]
 [10  9  5  5]
 [ 2  8 10  8]]
Array2: 
 [[ 6 10 10  3]
 [ 3 10  2  8]
 [ 1  5  9  5]]
addition: 
 [[12 14 17 13]
 [13 19  7 13]
 [ 3 13 19 13]]
Substraction: 
 [[ 0 -6 -3  7]
 [ 7 -1  3 -3]
 [ 1  3  1  3]]
multiplication: 
 [[36 40 70 30]
 [30 90 10 40]
 [ 2 40 90 40]]
division: 
 [[1.         0.4        0.7        3.33333333]
 [3.33333333 0.9        2.5        0.625     ]
 [2.         1.6        1.11111111 1.6       ]]


 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum. -->

In [ ]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1,17).reshape((4,4))
print("Array: \n",array)

row_sum = np.sum(array,axis=1)
print("row_wise_sum: ",row_sum)
column_sum = np.sum(array,axis=0)
print("column_wise_sum: ",column_sum)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row_wise_sum:  [10 26 42 58]
column_wise_sum:  [28 32 36 40]


 ### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array. 

In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers

array = np.random.randint(1,11,size=((5,5)))
print("Array: \n",array)

mean = np.mean(array)
print("mean is: ",mean)

median = np.median(array)
print("median is: ",median)

std_dev = np.std(array)
print("standard deviation: ",std_dev)

var = np.var(array)
print("variance is: ",var)

Array: 
 [[ 2  8  6  1  1]
 [ 7  2  8  7  8]
 [ 6  8  8  2  8]
 [ 1  4  9  6 10]
 [ 7  7  8  5  9]]
mean is:  5.92
median is:  7.0
standard deviation:  2.7845286854331377
variance is:  7.753599999999999


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [ ]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9

array = np.arange(1,10).reshape(3,3)
print("array: \n",array)

mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean)/std_dev
print("normalized array: \n",normalized_array)

array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
normalized array: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


 ### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting. 

In [ ]:
# # Create a NumPy array of shape (3, 3) filled with random integers
araay = np.random.randint(1,11,size=(3,3))
print("array: \n",array)

array1 = np.random.randint(1,11,size=(3,))
print("1D array: \n",array1)

#broadcasting --> this is 2d array + 1d array brodcasting

result = array + array1
print("broadcasted array: \n",result)



array: 
 [[ 2  5  3]
 [ 3 10  1]
 [10 10  3]]
1D array: 
 [3 6 3]
broadcasted array: 
 [[ 5 11  6]
 [ 6 16  4]
 [13 16  6]]


 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 1  6  5  4]
 [ 8  7  8  6]
 [ 8  3  1  5]
 [ 5  8  1 10]]
1D array:
[10  3  4  2]
Resulting array:
[[-9 -4 -5 -6]
 [ 5  4  5  3]
 [ 4 -1 -3  1]
 [ 3  6 -1  8]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues. 

In [ ]:
# Create a NumPy array of shape (3, 3) representing a matrix

array = np.random.randint(1,11,size=((3,3)))
print("matrix: \n",array)

det = np.linalg.det(array)
print("determinant: \n",det)

inv = np.linalg.inv(array)
print("inverse: \n",inv)

eg = np.linalg.eigvals(array)
print("eigen values: \n",eg)


Original matrix:
[[10  9  1]
 [ 6  2  7]
 [ 8 10 10]]
Determinant: -492.0000000000003
Inverse:
[[ 0.10162602  0.16260163 -0.12398374]
 [ 0.00813008 -0.18699187  0.1300813 ]
 [-0.08943089  0.05691057  0.06910569]]
Eigenvalues: [20.42959662  5.75503561 -4.18463223]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays. 

In [68]:
# # Create two NumPy arrays of shape (2, 3) and (3, 2)

array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

matrix_mult = np.dot(array1,array2)
print("matrix_mult is: \n",matrix_mult)

Array 1:
[[10 10  1]
 [10  2  5]]
Array 2:
[[8 1]
 [8 7]
 [8 1]]
matrix_mult is: 
 [[168  81]
 [136  29]]


 ### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [ ]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5). -->

In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array. 

In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10. 

In [ ]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age. 

In [ ]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points. 

In [ ]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

 ### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements. 

In [ ]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)