## Naive Baye's Machine Learning Algorithms Implementation

In [1]:
from sklearn.datasets import load_iris

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X,y=load_iris(return_X_y=True)

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

In [10]:
from sklearn.naive_bayes import GaussianNB

In [11]:
gnb=GaussianNB()

In [12]:
gnb.fit(X_train,y_train)

GaussianNB()

In [13]:
y_pred=gnb.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [17]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [52]:
df = sns.load_dataset('tips')

In [53]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [54]:
df.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [55]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [56]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [57]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [58]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [59]:
df.drop('size',axis=1,inplace=True)

In [60]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time'], dtype='object')

In [61]:
X = df[['total_bill', 'tip', 'sex','day','time']]
y = df['smoker']

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.10,random_state=10)

In [63]:
## performing label encoding 
from sklearn.preprocessing import LabelEncoder
l1= LabelEncoder()
l2= LabelEncoder()

X_train['sex'] = l1.fit_transform(X_train['sex'])
X_train['time'] = l2.fit_transform(X_train['time'])

X_train.head()


total_bill   tip  sex   day  time
136       10.33  2.00    0  Thur     1
76        17.92  3.08    1   Sat     0
119       24.08  2.92    0  Thur     1
120       11.69  2.31    1  Thur     1
59        48.27  6.73    1   Sat     0

In [64]:
X_test['sex'] = l1.transform(X_test['sex'])
X_test['time'] = l2.transform(X_test['time'])
X_test.head()

total_bill   tip  sex  day  time
162       16.21  2.00    0  Sun     0
60        20.29  3.21    1  Sat     0
61        13.81  2.00    1  Sat     0
63        18.29  3.76    1  Sat     0
69        15.01  2.09    1  Sat     0

#### whenever we are performing column transformations on multiple column and using different techniques we use column transformation

in this case we are using column transformation with single transformation technique and that is one hot encoding. Further in random forest we have used multiple transformation techinque using column transformation 

In [65]:
## performing one hot encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers = [('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')

In [66]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

X_train = ct.fit_transform(X_train)

In [67]:
X_train

array([[ 0.  ,  0.  ,  1.  , 10.33,  2.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  3.08,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 24.08,  2.92,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 11.69,  2.31,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 48.27,  6.73,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 29.93,  5.07,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 28.17,  6.5 ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  8.77,  2.  ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 12.66,  2.5 ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 19.82,  3.18,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 12.9 ,  1.1 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 20.65,  3.35,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , 12.16,  2.2 ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 20.49,  4.06,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 38.01,  3.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 19.44,  3.  ,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 45.35,  3.5 ,  1.  ,  0.  ],
       [ 0.  ,

In [73]:
# Recreate X_test from the original DataFrame to ensure it has the correct columns and types
X_test = df[['total_bill', 'tip', 'sex', 'day', 'time']].iloc[y_test.index]

# Apply label encoding to 'sex' and 'time' columns
X_test['sex'] = l1.transform(X_test['sex'])
X_test['time'] = l2.transform(X_test['time'])

# Now apply the ColumnTransformer
X_test = ct.transform(X_test)
X_test

array([[ 0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  3.21,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 25.89,  5.16,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 24.06,  3.6 ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  7.56,  1.44,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 30.14,  3.09,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , 16.49,  2.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , 18.64,  1.36,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 14.52,  2.  ,  0.  ,  1.  ],
       [ 0.  ,

In [48]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, y_train)

GaussianNB()

In [49]:
y_pred =gnb.predict(X_test)

In [50]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8
[[11  2]
 [ 3  9]]
              precision    recall  f1-score   support

          No       0.79      0.85      0.81        13
         Yes       0.82      0.75      0.78        12

    accuracy                           0.80        25
   macro avg       0.80      0.80      0.80        25
weighted avg       0.80      0.80      0.80        25

